<?php

return [
    'SITE_NAME' => 'He Thong Ban DT - Admin page',
    'ADMIN_LOGIN_ROUTE' => ADMIN_LOGIN_ROUTE,
    'ADMIN_LOGIN_AUTH_ROUTE' => ADMIN_LOGIN_AUTH_ROUTE,
    'ADMIN_REGISTER_ROUTE' => ADMIN_REGISTER_ROUTE,
    'ADMIN_REGISTER_AUTH_ROUTE' => ADMIN_REGISTER_AUTH_ROUTE,
];
